[package]
name = "jinshin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
data-encoding = "2.6.0"
regex = "1.11.0"
ring = "0.17.8"
walkdir = "2.5.0"

